customer: mcc
vertical: mrc
multistage: true
services:
- id: seleniumtest
  type: dockerfile
#  scale: single
  perStageConfiguration: true
  stageConfig:

    pp:
      replicas: 1
      resources:
        requests:
          memory: 800Mi
          cpu: "0.1"
        limits:
          memory: 1400Mi
          cpu: "1.5"

  check: true
  probe:
    initialdelay: 5

watchers:
- catalin.morariu@metrosystems.net

slack-channels:
- '@catalin.morariu'



