server:
  address: ${DRP_CF_HTTP_ADDR:0.0.0.0}
  port: ${DRP_CF_HTTP_PORT:8099}
logging:
  config: classpath:logback-json.xml

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    serialization:
      write_dates_as_timestamps: false

management:
  endpoints:
    # disable everything which is not enable explicitly
    enabled-by-default: false
  endpoint:
    metrics.enabled: true
  health:
    defaults.enabled: true
    db.enabled: true
    diskspace.enabled: true
  metrics:
    export.datadog.enabled: false
